# Numpy Arrays

`numpy` arrays are fast... 

### numpy arrays are fast

In [2]:
import numpy as np

In [5]:
big_list = list(range(10000000))
%timeit sum(big_list)

10 loops, best of 3: 85.4 ms per loop


In [4]:
import numpy as np
big_array = np.array(range(10000000))
%timeit np.sum(big_array)

100 loops, best of 3: 7.17 ms per loop


### Compare and contrast these two results

In [15]:
some_array = np.array([1,2,3])
print(some_array)
print(5*some_array)

[1 2 3]
[ 5 10 15]


In [16]:
some_list = [1,2,3]
print(some_list)
print(5*some_list)

[1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
you can do math across arrays

### Numpy math 

In [17]:
import math
math.sin(some_list)

TypeError: a float is required

In [18]:
np.sin(some_array)

array([ 0.84147098,  0.90929743,  0.14112001])

In [21]:

some_array = np.array([1,2,3,4,5])
print(some_array[0])
print(some_array[1:])
print(some_array[:-2])
print(some_array[:])


1
[2 3 4 5]
[1 2 3]
[1 2 3 4 5]


### X

you can make multi-dimensional arrays

In [19]:
print(np.zeros((3,5)))
print("")
print(np.ones((3,5)))
print("")
print(np.array([[0,1,2],[3,4,5],[6,7,8]]))

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


You can slice multi-dimensonal arrays

In [32]:

some_array = np.array([[1,2,3],[4,5,6]])
print(some_array)
print("")
print(some_array[0])
print("")
print(some_array[1])
print("")
print(some_array[0,0])
print("")
print(some_array[0,:])
print("")
print(some_array[:,:])

[[1 2 3]
 [4 5 6]]

[1 2 3]

[4 5 6]

1

[1 2 3]

[[1 2 3]
 [4 5 6]]
